name: CI

on:
  push:
    branches: [main, master]

env:
  REGISTRY: "cr.selcloud.ru/ne4chelovek"
  IMAGE_NAME: "mikle"
  COMPOSE_PROJECT_NAME: "mikle-app"
  DEPLOY_DIR: "/opt/mikle"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}

      - name: Build and push main image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG_NAME \
            -f Dockerfile .

      - name: Build and push migrator image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-migrator:$TAG_NAME \
            -f migration.Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp docker-compose.prod.yml deploy/
          cp -r migrations deploy/

          # Create .env file
          cat <<EOF > deploy/.env
          TAG=$(echo $GITHUB_SHA | head -c7)
          PG_DATABASE_NAME=${{ secrets.DB_NAME }}
          PG_USER=${{ secrets.DB_USER }}
          PG_PASSWORD=${{ secrets.DB_PASSWORD }}
          PG_PORT=5431
          MIGRATION_DIR=./migrations
          EOF

      - name: Upload files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "deploy/*"
          target: ${{ env.DEPLOY_DIR }}
          strip_components: 1

      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ env.DEPLOY_DIR }}
            
            # Login to registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ env.REGISTRY }}
            
            # Deploy
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            # Run migrations
            docker compose -f docker-compose.prod.yml run --rm migrator