name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/ne4chelovek"
  IMAGE_NAME: "mikle"
  CONTAINER_NAME: "mikle-server-container"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Create certs directory
        run: mkdir -p certs

      - name: Write certificate files from secrets
        run: |
          echo "${{ secrets.SERVICE_KEY }}" > certs/service.key
          echo "${{ secrets.SERVICE_PEM }}" > certs/service.pem

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f Dockerfile .

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
      - name: Deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)

            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

            # Create .env file for production
            echo "TAG=$TAG_NAME" > .env
            echo "PG_DATABASE_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "PG_USER==${{ secrets.DB_USER }}" >> .env
            echo "PG_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "PG_PORT=5431" >> .env
            echo "MIGRATION_DIR=./migrations" >> .env

            # Create docker-compose.yml
            cat << 'EOF' > docker-compose.yml
            version: '3.8'

            volumes:
              postgres_volume:

            services:
              app:
                image: ${REGISTRY}/${IMAGE_NAME}:${TAG}
                ports:
                  - "9070:9070"
                depends_on:
                  - pg-chat
                environment:
                  DB_HOST: pg-chat
                  DB_PORT: ${PG_PORT}
                  DB_NAME: ${PG_DATABASE_NAME}
                  DB_USER: ${PG_USER}
                  DB_PASSWORD: ${PG_PASSWORD}

              pg-chat:
                image: postgres:14-alpine3.19
                environment:
                  POSTGRES_DB: ${PG_DATABASE_NAME}
                  POSTGRES_USER: ${PG_USER}
                  POSTGRES_PASSWORD: ${PG_PASSWORD}
                ports:
                  - "${PG_PORT}:5432"
                volumes:
                  - postgres_volume:/var/lib/postgresql/data

              migrator:
                build:
                  context: .
                  dockerfile: migration.Dockerfile
                restart: on-failure
                depends_on:
                  - pg-chat
                environment:
                  DB_HOST: pg-chat
                  DB_PORT: ${PG_PORT}
                  DB_NAME: ${PG_DATABASE_NAME}
                  DB_USER: ${PG_USER}
                  DB_PASSWORD: ${PG_PASSWORD}
                  MIGRATION_DIR: ${MIGRATION_DIR}
            EOF

            # Stop and remove old containers
            docker compose down || true

            # Pull new images and start services
            docker compose pull
            docker compose up -d