name: CI

on:
  push:
    branches: [main, master]

env:
  REGISTRY: "cr.selcloud.ru/ne4chelovek"
  IMAGE_NAME: "mikle"
  COMPOSE_PROJECT_NAME: "mikle-app"
  DEPLOY_DIR: "/root"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare certificates
        run: |
          mkdir -p certs
          echo "${{ secrets.SERVICE_KEY }}" > certs/service.key
          echo "${{ secrets.SERVICE_PEM }}" > certs/service.pem
          chmod -R 700 certs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}

      - name: Build and push main image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG_NAME \
            -f Dockerfile .

      - name: Build and push migrator image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-migrator:$TAG_NAME \
            -f migration.Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp docker-compose.yml deploy/
          cp -r migrations deploy/
          
          # Create .env file
          cat <<EOF > deploy/.env
          TAG=$(echo $GITHUB_SHA | head -c7)
          REGISTRY=${{ env.REGISTRY }}
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          PG_DATABASE_NAME=${{ secrets.DB_NAME }}
          PG_USER=${{ secrets.DB_USER }}
          PG_PASSWORD=${{ secrets.DB_PASSWORD }}
          PG_PORT=5431
          MIGRATION_DIR=./migrations
          EOF

      - name: Upload files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "deploy/*"
          target: ${{ env.DEPLOY_DIR }}

      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.0
        with:
          script: |
            cd ${{ env.DEPLOY_DIR }}

            docker compose stop app migrator || true
            docker compose rm -f app migrator || true

            docker compose up -d --no-deps app migrator